= Termene și condiții

1. Soft Extend SRL declară și garantează că PACHETUL SOFTWARE de Localizare România pentru Microsoft Dynamics 365 Business Central, a fost supus validării funcționale în raport cu prevederile legislației fiscale românești în vigoare la data livrării. 
2. Furnizorul își asumă responsabilitatea că soluția este conformă cu cadrul normativ aplicabil (inclusiv, dar fără a se limita la, Codul Fiscal, reglementările contabile OMFP și ordinele ANAF aferente) și este pe deplin compatibilă cu versiunea de Business Central activă.
3. PACHETUL SOFTWARE de Localizare România pentru Microsoft Dynamics 365 Business Central, este și rămâne proprietatea exclusivă a Soft Extend SRL. 
4. Beneficiarul are doar drept de utilizare (licență neexclusivă, netransferabilă, revocabilă) pe perioada de  inchiriere. 
5. Este interzisă reproducerea, modificarea, distribuirea sau decompilarea software-ului fără acordul scris al Soft Extend SRL. 
6. Beneficiarul poate denunța unilateral prezentul pachet software cu cel puțin 3 luni calendaristice complete înainte de data încetării contractului. Preavizul începe să curgă de la prima zi a lunii calendaristice următoare comunicării notificării. 
7. Soft Extend SRL poate denunța unilateral prezentul act adițional cu un preaviz scris transmis Beneficiarului cu cel puțin 3 luni calendaristice complete înainte de data încetării contractului. Preavizul începe să curgă de la prima zi a lunii calendaristice următoare comunicării notificării. În această perioadă, Furnizorul se angajează să asigure, la cerere, suport Beneficiarului pentru eventuala tranziție la un alt produs similar cu PACHETUL SOFTWARE, aflat în proprietatea Beneficiarului sau furnizat de o terță parte. 
8. Încetarea prezentului act adițional, indiferent de motivul încetării (denunţare unilaterală, reziliere, anulare etc.), nu exonereaza Beneficiarul de obligația de plata către Furnizor a tuturor sumelor restante şi/sau penalităţile de întârziere aferente. 
9. La incetarea perioadei de închiriere, Beneficiarul nu va mai avea voie sa folosească PACHETUL SOFTWARE și se angajează să permită Furnizorului să dezinstaleze PACHETUL SOFTWARE. Eventualele date stocate în baza de date, inclusiv XML-urile și logurile generate în ERP, nu vor fi sterse și vor putea fi în continuare accesate de beneficiar folosind alte produse software capabile sa acceseze si sa citeasca din baza de date.   
10. Furnizorul poate ajusta tariful pentru PACHETUL SOFTWARE livrat în regim de închiriere/licență, cu o notificare prealabilă transmisă Beneficiarului cu minimum 2 luni calendaristice complete înainte de data propusă pentru intrarea în vigoare a noilor tarife. Noile prețuri vor fi aplicabile doar cu acordul scris al ambelor părți. În lipsa acestuia, contractul continuă cu tariful anterior sau poate fi denunțat de către oricare dintre părți, cu respectarea termenului de preaviz contractual.
